### ISSUE TITLE
Update button doesn't do anything on iOS

### ISSUE THREAD

**Issue by abhayastudios** [chronogolf/nativescript-store-update#27]
So I got the plugin to detect a newer version in the Apple Store, triggering the dialog showing a `Skip` and `Update` button. However, if I tap `Update` nothing happens. I also tried the demo project which has the same behavior. 

Is this the intended behavior or am I missing something? Is there a proper way to catch a tap on the `Update` and somehow tigger opening the AppStore?

Thanks!

**Comment by SBats** [comment]
You're right this is indeed a bug too. :(
The expected behaviour is for the platform store to be open at the app apge
(see [this line](https://github.com/chronogolf/nativescript-store-update/blob/master/src/store-update.ios.ts#L24))
Unfortunately I don't work on Nativescript apps at the moment. I'll try to give a look, but I have a hard time finding time for that. In the meantime if you ever found anything or a hint, don't hesitate to post it here.
Sorry about that.

**Comment by abhayastudios** [comment]
I stand corrected! As it turns out, v1.0.2 opens the AppStore just fine on iOS. I might have tried it on the iOS simulator which of course doesn't have access to the AppStore...

By the way, I saw that the config already allows for defining an `onConfirmed` function, which could be cool in case people want to take a different course of action. May I suggest it is added to the docs?

Cheers!
